### ISSUE TITLE
Does ssi-types need to depend on ssi-sdk-ext.jwt-service?

### ISSUE THREAD

**Issue by TimoGlastra** [Sphereon-Opensource/SSI-SDK#252]
It seems the ssi-types package now depends on `ssi-sdk-ext.jwt-service`, which pulls in a lot of extra dependencies. Is there a reason for the ssi-types to depend on this package? 

I couldn't find any usage of it, besides it being added to the package.json ("@sphereon/ssi-sdk-ext.jwt-service")

Also might it make sense to at some point move the ssi-types out of the ssi-sdk? As it seems ssi-types sits at the bottom, on top there's the open source unopiniated libs (PEX, OID4VCI, OID4VP) and then on top of that is the opiniated SDK (ssi-sdk).

I understand the need for shared types, but if you're not using the ssi-sdk the relation between types/sdk/opensource libs doesn't always make sense.

**Comment by nklomp** [comment]
Hmzz, not sure how that happened, as ssi-types should have minimal dependencies given its nature. Even the mdl-mdoc dep is a temp dep until we have proper types in there. Will fix that.

ssi-types is not part of the SDK packages. It just lives in the SDK repo because the SDK also heavily relies on these types and thus can make references from in the workspace. But for all intents and purposes the package is not part of the SDK. You can also see that as the name is not @sphereon/ssi-sdk.[package] or @sphereon/ssi-sdk-ext.[package] but @sphereon/ssi-types. So I am not sure I entirely understand the problem. 

To be clear, the above dep was made by someone and should never have happened. The mdl-mdoc will go away soon, leaving only some small external deps left. So what doesn't make sense in that relation?

**Comment by sanderPostma** [comment]
Just tried it, it builds fine without that dep

**Comment by TimoGlastra** [comment]
Seems to be resolved :)
