### ISSUE TITLE
JWT is created with incorrect alg when making Authentication Response JWT

### ISSUE THREAD

**Issue by niwim** [Sphereon-Opensource/ssi-sdk#46]
Trying to use agent.sendSiopAuthenticationResponse() the authentication fails on the RP side due to trying incorrect public key format (trying ES256K when it is supposed to be EdDSA)

Error:
`Error: no_suitable_keys: DID document for did:key:z6MkwVRpJ1AHXrb3z1Ao59a87MB6NqvUiseQ9XnVDf7RFE3K does not have public keys for ES256K`

The issue seems to be down to the following line 

https://github.com/Sphereon-Opensource/ssi-sdk/blob/b28b1f9db47b2c1669858b6cb5b127a8df4a3d31/packages/did-auth-siop-op-authenticator/src/session/OpSession.ts#L239

`identifier.controllerKeyId`

where did-siop-auth package expects a did-type formatted key:

https://github.com/Sphereon-Opensource/did-auth-siop/blob/a5ca3e90e4a1d978167bdb6b53b236b9cd0fd12f/src/main/functions/DidJWT.ts#L149

`isEd25519DidKeyMethod(payload.kid)`

However, Veramo provides a public key hex reference instead of a did-url

I'm not sure if this is an issue with this package or Veramo, I'm still struggling a bit to understand all of the keys to be honest...

**Comment by nklomp** [comment]
Hi @niwim . Although the fix was in yesterday, I wanted to tested it a bit with https://github.com/Sphereon-Opensource/did-siop-auth-web-demo as well, which is a demo webapp we use together with our SSI-SDK and Wallet (which will also become Open-Source).

If you update to @sphereon/ssi-sdk-did-auth-siop-authenticator version 0.6.1-next.9 and to @sphereon/did-auth-siop version 0.2.12 it should be fixed.

Please re-open or create a new ticket if you still encounter issues
